# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68bcc5b5e0d81c2af83898df387ab1427c37d34598eb1f931bbeb6d97bff3194eff8dfc7096967f7687c5ef7283f4529d301e1d616a43531cc019bf8add8c72b

test:
  secret_key_base: 0c17bcc90030adda9b1565a336517bdc88b5790cf4a7527b57fc84c2c3317e4c1d15d7c6cff5fbf15e99429c28cc591cc8e524cc7a1824db0c8fc181b2aa48cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
